import { OroStoreConfig, OroStoreConfigApiData } from '../../../../types/store-config';

export const storeConfigData: OroStoreConfigApiData[] = [
    {
        type: 'tf_config',
        id: 'oro_ui.application_url',
        attributes: {
            value: 'https://aligent.oro-cloud.com',
        },
    },
    {
        type: 'tf_config',
        id: 'oro_pricing_pro.default_currency',
        attributes: {
            value: 'AUD',
        },
    },
    {
        type: 'tf_config',
        id: 'oro_sale.contact_details',
        attributes: {
            value: '',
        },
    },
];

export const getMockOroStoreConfig = (): OroStoreConfig => {
    return {
        id: '1',
        type: 'StoreConfig',
        attributes: {
            id: '1',
            paypal_express: {
                in_context_config: {
                    in_context_id: '_',
                    merchant_id: '_',
                    client_config: {
                        button: '_',
                        environment: '_',
                        is_guest_checkout_allowed: '_',
                        is_visible_on_product_page: '_',
                        locale: '_',
                        merchant_id: '_',
                        styles: [
                            {
                                label: '_',
                                value: '_',
                            },
                        ],
                    },
                },
                billing_agreement_code: '_',
                is_context_checkout: '_',
                paylater_enabled: '_',
                payment_acceptance_mark_href: '_',
                payment_acceptance_mark_src: '_',
                redirect_url: '_',
                sdk_url: '_',
            },
            send_friend: {
                enabled_for_customers: true,
                enabled_for_guests: true,
            },
            store_information: {
                city: '_',
                country_id: '_',
                country_name: '_',
                hours: '_',
                merchant_vat_number: '_',
                name: '_',
                phone: '_',
                postcode: '_',
                region_id: '_',
                region_name: '_',
                street_line1: '_',
                street_line2: '_',
            },

            absolute_footer: '_',
            adyen_checkout_frontend_region: '_',
            adyen_client_key_live: '_',
            adyen_client_key_test: '_',
            adyen_demo_mode: true,
            adyen_has_holder_name: true,
            adyen_holder_name_required: true,
            adyen_oneclick_card_mode: '_',
            adyen_return_path_error: '_',
            adyen_title_renderer: '_',
            afterpaypay_active: '_',
            afterpaypay_api_enable_cta_cart_page: '_',
            afterpaypay_api_enable_cta_mini_cart: '_',
            afterpaypay_api_enable_cta_product_page: '_',
            afterpaypay_api_max_order_total: '_',
            afterpaypay_api_min_order_total: '_',
            afterpaypay_api_mode: '_',
            afterpaypay_title: '_',
            allow_gift_receipt: '_',
            allow_gift_wrapping_on_order: '_',
            allow_gift_wrapping_on_order_items: '_',
            allow_guests_to_write_product_reviews: '_',
            allow_items: '_',
            allow_order: '_',
            allow_printed_card: '_',
            autocomplete_on_storefront: true,
            base_currency_code: '_',
            base_link_url: '_',
            base_media_url: '_',
            base_static_url: '_',
            base_url: '_',
            braintree_cc_vault_active: '_',
            captcha_public_key_v2_checkbox: '_',
            captcha_public_key_v2_invisible: '_',
            captcha_public_key_v3_invisible: '_',
            captcha_type_contact: '_',
            captcha_type_customer_create: '_',
            captcha_type_customer_edit: '_',
            captcha_type_customer_forgot_password: '_',
            captcha_type_customer_login: '_',
            captcha_type_newsletter: '_',
            captcha_type_place_order: '_',
            captcha_type_product_review: '_',
            captcha_type_sendfriend: '_',
            captcha_type_wishlist_sharing: '_',
            cart_gift_wrapping: '_',
            cart_printed_card: '_',
            catalog_default_sort_by: '_',
            category_url_suffix: '_',
            check_money_order_enable_for_specific_countries: true,
            check_money_order_enabled: true,
            check_money_order_make_check_payable_to: '_',
            check_money_order_max_order_total: '_',
            check_money_order_min_order_total: '_',
            check_money_order_new_order_status: '_',
            check_money_order_payment_from_specific_countries: '_',
            check_money_order_send_check_to: '_',
            check_money_order_sort_order: 1,
            check_money_order_title: '_',
            cms_home_page: '_',
            cms_no_cookies: '_',
            cms_no_route: '_',
            code: '_',
            configurable_thumbnail_source: '_',
            contact_enabled: true,
            copyright: '_',
            default_description: '_',
            default_display_currency_code: '_',
            default_keywords: '_',
            default_title: '_',
            demonotice: 1,
            enable_multiple_wishlists: '_',
            front: '_',
            googleMapsAPIKey: '_',
            grid_per_page: 1,
            grid_per_page_values: '_',
            head_includes: '_',
            head_shortcut_icon: '_',
            header_logo_src: '_',
            is_default_store: true,
            is_default_store_group: true,
            list_mode: '_',
            list_per_page: 1,
            list_per_page_values: '_',
            locale: 'en_AU',
            logo_alt: '_',
            logo_height: 1,
            logo_width: 1,
            magento_reward_general_is_enabled: '_',
            magento_reward_general_is_enabled_on_front: '_',
            magento_reward_general_min_points_balance: '_',
            magento_reward_general_publish_history: '_',
            magento_reward_points_invitation_customer: '_',
            magento_reward_points_invitation_customer_limit: '_',
            magento_reward_points_invitation_order: '_',
            magento_reward_points_invitation_order_limit: '_',
            magento_reward_points_newsletter: '_',
            magento_reward_points_order: '_',
            magento_reward_points_register: '_',
            magento_reward_points_review: '_',
            magento_reward_points_review_limit: '_',
            magento_wishlist_general_is_enabled: '_',
            maximum_number_of_wishlists: '_',
            minimum_password_length: '_',
            newsletter_enabled: true,
            no_route: '_',
            payment_payflowpro_cc_vault_active: '_',
            plpAddToCartEnabled: true,
            plpQtyModifierEnabled: true,
            printed_card_price: '_',
            product_reviews_enabled: '_',
            product_url_suffix: '_',
            pwa_base_url: '_',
            required_character_classes_number: '_',
            returns_enabled: '_',
            root_category_id: 1,
            root_category_uid: '1',
            sales_gift_wrapping: '_',
            sales_printed_card: '_',
            secure_base_link_url: '_',
            secure_base_media_url: 'https://aligent.oro-cloud.com',
            secure_base_static_url: '_',
            secure_base_url: '_',
            show_cms_breadcrumbs: 1,
            store_code: '1',
            store_group_code: '1',
            store_group_name: '_',
            store_name: '_',
            store_phone_number: '_',
            store_sort_order: 1,
            timezone: '_',
            title_prefix: '_',
            title_separator: '_',
            title_suffix: '_',
            use_store_in_url: true,
            website_code: '1',
            website_id: 1,
            website_name: '_',
            weight_unit: '_',
            welcome: '_',
            zero_subtotal_enable_for_specific_countries: true,
            zero_subtotal_enabled: true,
            zero_subtotal_new_order_status: '_',
            zero_subtotal_payment_action: '_',
            zero_subtotal_payment_from_specific_countries: '_',
            zero_subtotal_sort_order: 1,
            zero_subtotal_title: '_',
        },
    };
};
