import { StoreConfig as AcStoreConfig } from '@aligent/orocommerce-resolvers';

export const transformedStoreConfig: AcStoreConfig = {
    __typename: 'StoreConfig',
    pwa_base_url: 'https://aligent.oro-cloud.com',
    default_display_currency_code: 'AUD',
    contact_enabled: false,
    newsletter_enabled: false,
    returns_enabled: '',
    id: null,
    use_store_in_url: true,
    website_code: '1',
    website_id: 1,
    root_category_id: 1,
    root_category_uid: 'null',
    secure_base_media_url: 'https://aligent.oro-cloud.com',
    plpAddToCartEnabled: true,
    plpQtyModifierEnabled: true,
    locale: 'en-AU',
    is_default_store: true,
    is_default_store_group: true,
    list_per_page: 1,
    check_money_order_enable_for_specific_countries: true,
    autocomplete_on_storefront: true,
    check_money_order_enabled: true,
    category_url_suffix: '',
    grid_per_page: 24,
    captcha_type_contact: null,
    captcha_type_customer_create: null,
    captcha_type_customer_forgot_password: null,
    captcha_type_customer_login: null,
    captcha_type_newsletter: null,
    captcha_type_product_review: null,
    captcha_type_sendfriend: null,
    captcha_type_place_order: null,
    captcha_public_key_v2_checkbox: null,
    captcha_public_key_v2_invisible: null,
    captcha_public_key_v3_invisible: null,
    captcha_type_wishlist_sharing: null,
    magento_wishlist_general_is_enabled: null,
    store_code: null,
    paypal_express: {
        billing_agreement_code: null,
        in_context_config: {
            client_config: {
                button: null,
                environment: null,
                is_guest_checkout_allowed: null,
                is_visible_on_product_page: null,
                locale: null,
                merchant_id: null,
                styles: [{ label: null, value: null }],
            },
            merchant_id: null,
        },
        is_context_checkout: null,
    },
    product_reviews_enabled: null,
};
