import { StoreConfig as AcStoreConfig } from '@aligent/orocommerce-resolvers';

export const transformedStoreConfig: AcStoreConfig = {
    pwa_base_url: 'https://aligent.oro-cloud.com',
    default_display_currency_code: 'AUD',
    contact_enabled: true,
    newsletter_enabled: true,
    returns_enabled: '',
    id: null,
    category_url_suffix: null,
    grid_per_page: null,
    plpAddToCartEnabled: null,
    plpQtyModifierEnabled: null,
    captcha_type_contact: null,
    captcha_type_customer_create: null,
    captcha_type_customer_forgot_password: null,
    captcha_type_customer_login: null,
    captcha_type_newsletter: null,
    captcha_type_product_review: null,
    captcha_type_sendfriend: null,
    captcha_type_place_order: null,
    captcha_public_key_v2_checkbox: null,
    captcha_public_key_v2_invisible: null,
    captcha_public_key_v3_invisible: null,
    captcha_type_wishlist_sharing: null,
    magento_wishlist_general_is_enabled: null,
    store_code: null,
    paypal_express: {
        billing_agreement_code: null,
        in_context_config: {
            client_config: {
                button: null,
                environment: null,
                is_guest_checkout_allowed: null,
                is_visible_on_product_page: null,
                locale: null,
                merchant_id: null,
                styles: [{ label: null, value: null }],
            },
            merchant_id: null,
        },
        is_context_checkout: null,
    },
    product_reviews_enabled: null,
    locale: null,
};
