export const outputProducts = [
    {
        categories: [
            {
                type: 'CATEGORY',
                __typename: 'CategoryTree',
                created_at: '2022-08-26T10:34:23Z',
                id: 1,
                uid: 'eyJpZCI6IjEiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                staged: true,
                name: 'All Products',
                level: 1,
                redirect_code: 0,
                description: null,
                meta_title: null,
                meta_description: null,
                meta_keywords: null,
                url_path: null,
                image: null,
            },
            {
                type: 'CATEGORY',
                __typename: 'CategoryTree',
                created_at: '2023-10-27T01:41:03Z',
                id: 5,
                uid: 'eyJpZCI6IjUiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                staged: true,
                name: 'Women',
                level: 2,
                redirect_code: 0,
                description: null,
                meta_title: null,
                meta_description: null,
                meta_keywords: null,
                url_path: '/women',
                image: null,
            },
            {
                type: 'CATEGORY',
                __typename: 'CategoryTree',
                created_at: '2023-10-27T01:41:32Z',
                id: 6,
                uid: 'eyJpZCI6IjYiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                staged: true,
                name: 'Tops',
                level: 3,
                redirect_code: 0,
                description: null,
                meta_title: null,
                meta_description: null,
                meta_keywords: null,
                url_path: '/tops',
                image: null,
            },
            {
                type: 'CATEGORY',
                __typename: 'CategoryTree',
                created_at: '2023-10-27T01:41:50Z',
                id: 7,
                uid: 'eyJpZCI6IjciLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                staged: true,
                name: 'Hoodies & Sweatshirts',
                level: 4,
                redirect_code: 0,
                description: null,
                meta_title: null,
                meta_description: null,
                meta_keywords: null,
                url_path: '/hoodies-sweatshirts',
                image: null,
            },
        ],
        description: {
            __typename: 'ComplexTextValue',
            html: '<div id="isolation-scope-9g6aw0a9x3jbp8ftbuod16944" class="cms-wrapper"><div>Whether you&#039;re after energizing activity or eye-catching apparel, the Mona Pullover is what you want. You&#039;ll stay warm and look fashionable, wherever you are.</div><br/><div> </div><br/><div> • Light green heathered hoodie. </div><br/><div> • Long-Sleeve, pullover.</div><br/><div> • Long elliptical hem for extra coverage.</div><br/><div> • Deep button placket for layering.</div><br/><div> • Double rib design.</div><br/><div> • Mid layer, mid weight.</div><br/><div> • 98% Merino Wool / 2% Spandex</div></div>',
        },
        staged: true,
        uid: 'MTI=',
        custom_attributes: [],
        id: 12,
        media_gallery_entries: [
            {
                id: 23,
                label: 'product_original',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 1,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfb3JpZ2luYWw=',
            },
            {
                id: 24,
                label: 'product_gallery_popup',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_popup/098f408deb471e628613685fa97b1968/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 2,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9wb3B1cA==',
            },
            {
                id: 25,
                label: 'product_gallery_main',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_main/cfd646b508e8eaf0ad3fa52d426f48a6/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 3,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9tYWlu',
            },
            {
                id: 26,
                label: 'product_large',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_large/484cb95e4abcb58ccab27f13d1a6188b/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 4,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbGFyZ2U=',
            },
            {
                id: 27,
                label: 'product_extra_large',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_extra_large/611b34cf36199f7491b40a557dad14a9/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 5,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZXh0cmFfbGFyZ2U=',
            },
            {
                id: 28,
                label: 'product_medium',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_medium/c3f301e68dee27d69af5c17c4acfe7ea/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 6,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbWVkaXVt',
            },
            {
                id: 29,
                label: 'product_small',
                disabled: false,
                file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                position: 7,
                uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfc21hbGw=',
            },
        ],
        meta_title: null,
        meta_keyword: null,
        meta_description: null,
        name: 'Mona Pullover Hoodlie',
        price: null,
        price_range: {
            minimum_price: {
                regular_price: { currency: 'AUD', value: 57 },
                final_price: { currency: 'AUD', value: 57 },
                discount: { amount_off: 0 },
            },
            maximum_price: {
                regular_price: { currency: 'AUD', value: 57 },
                final_price: { currency: 'AUD', value: 57 },
            },
        },
        price_tiers: [],
        redirect_code: 0,
        rating_summary: 0,
        review_count: 0,
        related_products: null,
        sku: 'WH01',
        small_image: {
            url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
            label: 'wh01-green_main',
        },
        image: {
            url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
            label: 'wh01-green_main',
        },
        type: 'PRODUCT',
        stock_status: 'IN_STOCK',
        url_key: 'mona-pullover-hoodlie',
        url_suffix: '',
        reviews: {
            __typename: 'ProductReviews',
            items: [],
            page_info: { current_page: 0, page_size: 0, total_pages: 0 },
        },
        variants: [
            {
                attributes: [
                    { code: 'size_63313224a7189', label: 'S', uid: 'cw==' },
                    { code: 'size_633132c50db9e', label: 'yellow', uid: 'eWVsbG93' },
                ],
                product: {
                    id: 9,
                    __typename: 'SimpleProduct',
                    categories: [
                        {
                            __typename: 'CategoryTree',
                            created_at: '2022-08-26T10:34:23Z',
                            description: null,
                            id: 1,
                            image: null,
                            level: 1,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'All Products',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjEiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: null,
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:03Z',
                            description: null,
                            id: 5,
                            image: null,
                            level: 2,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Women',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjUiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/women',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:32Z',
                            description: null,
                            id: 6,
                            image: null,
                            level: 3,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Tops',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjYiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/tops',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:50Z',
                            description: null,
                            id: 7,
                            image: null,
                            level: 4,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Hoodies & Sweatshirts',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjciLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/hoodies-sweatshirts',
                        },
                    ],
                    custom_attributes: [],
                    description: {
                        __typename: 'ComplexTextValue',
                        html: '',
                    },
                    media_gallery_entries: [
                        {
                            id: 23,
                            label: 'product_original',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 1,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfb3JpZ2luYWw=',
                        },
                        {
                            id: 24,
                            label: 'product_gallery_popup',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_popup/098f408deb471e628613685fa97b1968/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 2,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9wb3B1cA==',
                        },
                        {
                            id: 25,
                            label: 'product_gallery_main',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_main/cfd646b508e8eaf0ad3fa52d426f48a6/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 3,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9tYWlu',
                        },
                        {
                            id: 26,
                            label: 'product_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_large/484cb95e4abcb58ccab27f13d1a6188b/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 4,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbGFyZ2U=',
                        },
                        {
                            id: 27,
                            label: 'product_extra_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_extra_large/611b34cf36199f7491b40a557dad14a9/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 5,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZXh0cmFfbGFyZ2U=',
                        },
                        {
                            id: 28,
                            label: 'product_medium',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_medium/c3f301e68dee27d69af5c17c4acfe7ea/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 6,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbWVkaXVt',
                        },
                        {
                            id: 29,
                            label: 'product_small',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 7,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfc21hbGw=',
                        },
                    ],
                    meta_description: null,
                    meta_keyword: null,
                    meta_title: null,
                    name: 'Yellow Small Aligent Hoodie',
                    price: null,
                    price_range: {
                        minimum_price: {
                            regular_price: { currency: 'AUD', value: 19 },
                            final_price: { currency: 'AUD', value: 19 },
                            discount: { amount_off: 0 },
                        },
                        maximum_price: {
                            regular_price: { currency: 'AUD', value: 19 },
                            final_price: { currency: 'AUD', value: 19 },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        __typename: 'ProductReviews',
                        items: [],
                        page_info: { current_page: 0, page_size: 0, total_pages: 0 },
                    },
                    review_count: 0,
                    sku: 'HOODIE-SY',
                    related_products: null,
                    small_image: {
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                        label: 'wh01-green_main',
                    },
                    image: {
                        label: 'wh01-green_main',
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                    },
                    staged: true,
                    stock_status: 'OUT_OF_STOCK',
                    type: 'PRODUCT',
                    uid: 'OQ==',
                    url_key: 'yellow-small-aligent-hoodie',
                    url_suffix: '',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    { code: 'size_63313224a7189', label: 'M', uid: 'bQ==' },
                    { code: 'size_633132c50db9e', label: 'purple', uid: 'cHVycGxl' },
                ],
                product: {
                    id: 7,
                    __typename: 'SimpleProduct',
                    categories: [
                        {
                            __typename: 'CategoryTree',
                            created_at: '2022-08-26T10:34:23Z',
                            description: null,
                            id: 1,
                            image: null,
                            level: 1,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'All Products',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjEiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: null,
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:03Z',
                            description: null,
                            id: 5,
                            image: null,
                            level: 2,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Women',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjUiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/women',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:32Z',
                            description: null,
                            id: 6,
                            image: null,
                            level: 3,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Tops',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjYiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/tops',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:50Z',
                            description: null,
                            id: 7,
                            image: null,
                            level: 4,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Hoodies & Sweatshirts',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjciLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/hoodies-sweatshirts',
                        },
                    ],
                    custom_attributes: [],
                    description: {
                        __typename: 'ComplexTextValue',
                        html: '',
                    },
                    media_gallery_entries: [
                        {
                            id: 23,
                            label: 'product_original',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 1,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfb3JpZ2luYWw=',
                        },
                        {
                            id: 24,
                            label: 'product_gallery_popup',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_popup/098f408deb471e628613685fa97b1968/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 2,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9wb3B1cA==',
                        },
                        {
                            id: 25,
                            label: 'product_gallery_main',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_main/cfd646b508e8eaf0ad3fa52d426f48a6/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 3,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9tYWlu',
                        },
                        {
                            id: 26,
                            label: 'product_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_large/484cb95e4abcb58ccab27f13d1a6188b/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 4,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbGFyZ2U=',
                        },
                        {
                            id: 27,
                            label: 'product_extra_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_extra_large/611b34cf36199f7491b40a557dad14a9/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 5,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZXh0cmFfbGFyZ2U=',
                        },
                        {
                            id: 28,
                            label: 'product_medium',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_medium/c3f301e68dee27d69af5c17c4acfe7ea/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 6,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbWVkaXVt',
                        },
                        {
                            id: 29,
                            label: 'product_small',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 7,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfc21hbGw=',
                        },
                    ],
                    meta_description: null,
                    meta_keyword: null,
                    meta_title: null,
                    name: 'Purple Medium Aligent Hoodie',
                    price: null,
                    price_range: {
                        minimum_price: {
                            regular_price: { currency: 'AUD', value: 14 },
                            final_price: { currency: 'AUD', value: 14 },
                            discount: { amount_off: 0 },
                        },
                        maximum_price: {
                            regular_price: { currency: 'AUD', value: 14 },
                            final_price: { currency: 'AUD', value: 14 },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        __typename: 'ProductReviews',
                        items: [],
                        page_info: { current_page: 0, page_size: 0, total_pages: 0 },
                    },
                    review_count: 0,
                    sku: 'HOODIE-MP',
                    related_products: null,
                    small_image: {
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                        label: 'wh01-green_main',
                    },
                    image: {
                        label: 'wh01-green_main',
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                    },
                    staged: true,
                    stock_status: 'IN_STOCK',
                    type: 'PRODUCT',
                    uid: 'Nw==',
                    url_key: 'purple-medium-aligent-hoodie',
                    url_suffix: '',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    { code: 'size_63313224a7189', label: 'M', uid: 'bQ==' },
                    { code: 'size_633132c50db9e', label: 'yellow', uid: 'eWVsbG93' },
                ],
                product: {
                    id: 6,
                    __typename: 'SimpleProduct',
                    categories: [
                        {
                            __typename: 'CategoryTree',
                            created_at: '2022-08-26T10:34:23Z',
                            description: null,
                            id: 1,
                            image: null,
                            level: 1,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'All Products',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjEiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: null,
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:03Z',
                            description: null,
                            id: 5,
                            image: null,
                            level: 2,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Women',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjUiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/women',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:32Z',
                            description: null,
                            id: 6,
                            image: null,
                            level: 3,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Tops',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjYiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/tops',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:50Z',
                            description: null,
                            id: 7,
                            image: null,
                            level: 4,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Hoodies & Sweatshirts',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjciLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/hoodies-sweatshirts',
                        },
                    ],
                    custom_attributes: [],
                    description: {
                        __typename: 'ComplexTextValue',
                        html: '',
                    },
                    media_gallery_entries: [
                        {
                            id: 23,
                            label: 'product_original',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 1,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfb3JpZ2luYWw=',
                        },
                        {
                            id: 24,
                            label: 'product_gallery_popup',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_popup/098f408deb471e628613685fa97b1968/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 2,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9wb3B1cA==',
                        },
                        {
                            id: 25,
                            label: 'product_gallery_main',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_main/cfd646b508e8eaf0ad3fa52d426f48a6/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 3,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9tYWlu',
                        },
                        {
                            id: 26,
                            label: 'product_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_large/484cb95e4abcb58ccab27f13d1a6188b/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 4,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbGFyZ2U=',
                        },
                        {
                            id: 27,
                            label: 'product_extra_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_extra_large/611b34cf36199f7491b40a557dad14a9/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 5,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZXh0cmFfbGFyZ2U=',
                        },
                        {
                            id: 28,
                            label: 'product_medium',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_medium/c3f301e68dee27d69af5c17c4acfe7ea/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 6,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbWVkaXVt',
                        },
                        {
                            id: 29,
                            label: 'product_small',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 7,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfc21hbGw=',
                        },
                    ],
                    meta_description: null,
                    meta_keyword: null,
                    meta_title: null,
                    name: 'Yellow Medium Aligent Hoodie',
                    price: null,
                    price_range: {
                        minimum_price: {
                            regular_price: { currency: 'AUD', value: 16 },
                            final_price: { currency: 'AUD', value: 16 },
                            discount: { amount_off: 0 },
                        },
                        maximum_price: {
                            regular_price: { currency: 'AUD', value: 16 },
                            final_price: { currency: 'AUD', value: 16 },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        __typename: 'ProductReviews',
                        items: [],
                        page_info: { current_page: 0, page_size: 0, total_pages: 0 },
                    },
                    review_count: 0,
                    sku: 'HOODIE-MY',
                    related_products: null,
                    small_image: {
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                        label: 'wh01-green_main',
                    },
                    image: {
                        label: 'wh01-green_main',
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                    },
                    staged: true,
                    stock_status: 'IN_STOCK',
                    type: 'PRODUCT',
                    uid: 'Ng==',
                    url_key: 'yellow-medium-aligent-hoodie',
                    url_suffix: '',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    { code: 'size_63313224a7189', label: 'S', uid: 'cw==' },
                    { code: 'size_633132c50db9e', label: 'purple', uid: 'cHVycGxl' },
                ],
                product: {
                    id: 10,
                    __typename: 'SimpleProduct',
                    categories: [
                        {
                            __typename: 'CategoryTree',
                            created_at: '2022-08-26T10:34:23Z',
                            description: null,
                            id: 1,
                            image: null,
                            level: 1,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'All Products',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjEiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: null,
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:03Z',
                            description: null,
                            id: 5,
                            image: null,
                            level: 2,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Women',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjUiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/women',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:32Z',
                            description: null,
                            id: 6,
                            image: null,
                            level: 3,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Tops',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjYiLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/tops',
                        },
                        {
                            __typename: 'CategoryTree',
                            created_at: '2023-10-27T01:41:50Z',
                            description: null,
                            id: 7,
                            image: null,
                            level: 4,
                            meta_description: null,
                            meta_keywords: null,
                            meta_title: null,
                            name: 'Hoodies & Sweatshirts',
                            redirect_code: 0,
                            staged: true,
                            type: 'CATEGORY',
                            uid: 'eyJpZCI6IjciLCJ0eXBlIjoibWFzdGVyY2F0YWxvZ2NhdGVnb3JpZXMifQ==',
                            url_path: '/hoodies-sweatshirts',
                        },
                    ],
                    custom_attributes: [],
                    description: {
                        __typename: 'ComplexTextValue',
                        html: '',
                    },
                    media_gallery_entries: [
                        {
                            id: 23,
                            label: 'product_original',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 1,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfb3JpZ2luYWw=',
                        },
                        {
                            id: 24,
                            label: 'product_gallery_popup',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_popup/098f408deb471e628613685fa97b1968/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 2,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9wb3B1cA==',
                        },
                        {
                            id: 25,
                            label: 'product_gallery_main',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_gallery_main/cfd646b508e8eaf0ad3fa52d426f48a6/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 3,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZ2FsbGVyeV9tYWlu',
                        },
                        {
                            id: 26,
                            label: 'product_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_large/484cb95e4abcb58ccab27f13d1a6188b/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 4,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbGFyZ2U=',
                        },
                        {
                            id: 27,
                            label: 'product_extra_large',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_extra_large/611b34cf36199f7491b40a557dad14a9/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 5,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfZXh0cmFfbGFyZ2U=',
                        },
                        {
                            id: 28,
                            label: 'product_medium',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_medium/c3f301e68dee27d69af5c17c4acfe7ea/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 6,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3RfbWVkaXVt',
                        },
                        {
                            id: 29,
                            label: 'product_small',
                            disabled: false,
                            file: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                            position: 7,
                            uid: 'aWQ6MjItZGltZW5zaW9uOnByb2R1Y3Rfc21hbGw=',
                        },
                    ],
                    meta_description: null,
                    meta_keyword: null,
                    meta_title: null,
                    name: 'Purple Small Aligent Hoodie',
                    price: null,
                    price_range: {
                        minimum_price: {
                            regular_price: { currency: 'AUD', value: 17 },
                            final_price: { currency: 'AUD', value: 17 },
                            discount: { amount_off: 0 },
                        },
                        maximum_price: {
                            regular_price: { currency: 'AUD', value: 17 },
                            final_price: { currency: 'AUD', value: 17 },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        __typename: 'ProductReviews',
                        items: [],
                        page_info: { current_page: 0, page_size: 0, total_pages: 0 },
                    },
                    review_count: 0,
                    sku: 'HOODIE-SP',
                    related_products: null,
                    small_image: {
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_small/5ffc023aed34cd80eccf6957058b520e/56/653b166935ea7214964398-wh01-green_main.jpg',
                        label: 'wh01-green_main',
                    },
                    image: {
                        label: 'wh01-green_main',
                        url: 'https://aligent.oro-cloud.com/media/cache/attachment/filter/product_original/1ce6569ddaa67bc2162be5030a1ac716/56/653b166935ea7214964398-wh01-green_main.jpg',
                    },
                    staged: true,
                    stock_status: 'IN_STOCK',
                    type: 'PRODUCT',
                    uid: 'MTA=',
                    url_key: 'purple-small-aligent-hoodie',
                    url_suffix: '',
                },
                __typename: 'ConfigurableVariant',
            },
        ],
        configurable_options: [],
        __typename: 'ConfigurableProduct',
    },
];
