import { BCOrderLineItem } from '../../../types';
import { CartItemInput } from '@mesh';

export const restCartLineItemData: BCOrderLineItem = {
    id: 50,
    order_id: 127,
    product_id: 492,
    variant_id: 516,
    order_pickup_method_id: 0,
    order_address_id: 29,
    name: 'Mona Pullover Hoodlie',
    name_customer: 'Mona Pullover Hoodlie',
    name_merchant: 'Mona Pullover Hoodlie',
    sku: 'WH01-M-Purple',
    upc: '',
    type: 'physical',
    base_price: '10.0000',
    price_ex_tax: '9.0900',
    price_inc_tax: '10.0000',
    price_tax: '0.9100',
    base_total: '20.0000',
    total_ex_tax: '18.1800',
    total_inc_tax: '20.0000',
    total_tax: '1.8200',
    weight: '1.0000',
    width: '21.0000',
    height: '21.0000',
    depth: '21.0000',
    quantity: 2,
    base_cost_price: '0.0000',
    cost_price_inc_tax: '0.0000',
    cost_price_ex_tax: '0.0000',
    cost_price_tax: '0.0000',
    is_refunded: false,
    quantity_refunded: 0,
    refund_amount: '0.0000',
    return_id: 0,
    wrapping_id: 0,
    wrapping_name: '',
    base_wrapping_cost: '0.0000',
    wrapping_cost_ex_tax: '0.0000',
    wrapping_cost_inc_tax: '0.0000',
    wrapping_cost_tax: '0.0000',
    wrapping_message: '',
    quantity_shipped: 0,
    event_date: '',
    fixed_shipping_cost: '0.0000',
    ebay_item_id: '',
    ebay_transaction_id: '',
    is_bundled_product: false,
    bin_picking_number: '',
    fulfillment_source: '',
    brand: 'Weller',
    applied_discounts: [],
    product_options: [
        {
            id: 29,
            option_id: 70,
            order_product_id: 50,
            product_option_id: 148,
            display_name: 'Color',
            display_name_customer: 'Color',
            display_name_merchant: 'Color',
            display_value: 'Purple',
            display_value_customer: 'Purple',
            display_value_merchant: 'Purple',
            value: '183',
            type: 'Swatch',
            name: 'Color1690452034-492',
            display_style: '',
        },
        {
            id: 30,
            option_id: 71,
            order_product_id: 50,
            product_option_id: 149,
            display_name: 'Size',
            display_name_customer: 'Size',
            display_name_merchant: 'Size',
            display_value: 'M',
            display_value_customer: 'M',
            display_value_merchant: 'M',
            value: '185',
            type: 'Multiple choice',
            name: 'Size1690452449-492',
            display_style: 'Radio Buttons',
        },
    ],
};

export const cartLineItem: CartItemInput = {
    quantity: 2,
    uid: 'UHJvZHVjdDo0OTI=',
    sku: 'VmFyaWFudDo1MTY=',
    selected_options: ['Y29uZmlndXJhYmxlLzcwLzE0OA==', 'Y29uZmlndXJhYmxlLzcxLzE0OQ=='],
};
