merger: stitching
sources:
  # - !include ../bigcommerce/take-flight-graphql-api.yml
  - !include ../bigcommerce/bc-graphql-api.yml

# additionalResolvers:
#   - '../bigcommerce/resolvers/resolver-definitions'

additionalEnvelopPlugins: '../bigcommerce/plugins/additional-plugins'

codegen:
  contextType: ../types#GraphQlContext

serve: !include serve-config.yml
#cache: !include cache-config.yml
