merger: stitching
sources:
  - !include ../bigcommerce/take-flight-graphql-api.yml
  - !include ../bigcommerce/bc-graphql-api.yml

additionalResolvers:
  - '../bigcommerce/resolvers/resolver-definitions'

additionalEnvelopPlugins: '../bigcommerce/plugins/additional-plugins'

codegen:
  contextType: ../types#GraphQlContext

serve: !include '${STAGE}/serve.yml'
cache: !include '${STAGE}/cache.yml'
