merger: stitching
sources:
  # - !include ../bigcommerce/take-flight-graphql-api.yml
  - !include ../bigcommerce/bc-graphql-api.yml

# additionalResolvers:
#   - '../bigcommerce/resolvers/resolver-definitions'

serve: !include serve-config.yml
