import { getDeNestedProductVariants } from '../products';
import { productsMock } from '../../bigcommerce/resolvers/mocks/products';
import { ConfigurableProduct } from '@mesh';

const expectResult = [
    {
        __typename: 'ConfigurableProduct',
        categories: [
            {
                uid: 'OA==',
                breadcrumbs: null,
                name: 'New Luma Yoga Collection',
                level: 3,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjE=',
                breadcrumbs: null,
                name: 'Women',
                level: 2,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjI=',
                breadcrumbs: [
                    {
                        category_uid: 'MjE=',
                        category_name: 'Women',
                        __typename: 'Breadcrumb',
                    },
                ],
                name: 'Tops',
                level: 3,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjU=',
                breadcrumbs: [
                    {
                        category_uid: 'MjE=',
                        category_name: 'Women',
                        __typename: 'Breadcrumb',
                    },
                    {
                        category_uid: 'MjI=',
                        category_name: 'Tops',
                        __typename: 'Breadcrumb',
                    },
                ],
                name: 'Hoodies & Sweatshirts',
                level: 4,
                redirect_code: 0,
                staged: false,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MzU=',
                breadcrumbs: null,
                name: 'Erin Recommends',
                level: 3,
                redirect_code: 0,
                staged: false,
                __typename: 'CategoryTree',
            },
        ],
        custom_attributes: [],
        description: {
            html: "Whether you're after energizing activity or eye-catching apparel, the Mona Pullover is what you want. You'll stay warm and look fashionable, wherever you are.<br /> <br /> &bull; Light green heathered hoodie. <br /> &bull; Long-Sleeve, pullover.<br /> &bull; Long elliptical hem for extra coverage.<br /> &bull; Deep button placket for layering.<br /> &bull; Double rib design.<br /> &bull; Mid layer, mid weight.<br /> &bull; 98% Merino Wool / 2% Spandex",
            __typename: 'ComplexTextValue',
        },
        id: 1046,
        media_gallery_entries: [
            {
                id: 1762,
                label: '',
                position: 1,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1763,
                label: '',
                position: 2,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1764,
                label: '',
                position: 3,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        meta_title: null,
        meta_keyword: null,
        meta_description: null,
        name: 'Mona Pullover Hoodlie',
        price: {
            regularPrice: {
                amount: {
                    currency: 'AUD',
                    value: 55,
                    __typename: 'Money',
                },
                __typename: 'Price',
            },
            __typename: 'ProductPrices',
        },
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            minimum_price: {
                discount: {
                    amount_off: 25,
                    percent_off: 45.45,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 30,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 55,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        price_tiers: [],
        rating_summary: 87,
        review_count: 3,
        related_products: [
            {
                categories: [],
                name: 'Affirm Water Bottle ',
                id: 15,
                sku: '24-UG06',
                url_key: 'affirm-water-bottle',
                url_suffix: '.html',
                small_image: {
                    url: 'https://take-flight-ew3k5nq-ekxw7lyelhava.ap-4.magentosite.cloud/media/catalog/product/cache/8f3d2e129ba9bc6369f4f94872c5b9a2/u/g/ug06-lb-0.jpg',
                    __typename: 'ProductImage',
                },
                price: {
                    regularPrice: {
                        amount: {
                            currency: 'AUD',
                            value: 7,
                            __typename: 'Money',
                        },
                        __typename: 'Price',
                    },
                    __typename: 'ProductPrices',
                },
                price_range: {
                    minimum_price: {
                        discount: {
                            amount_off: 0,
                            __typename: 'ProductDiscount',
                        },
                        final_price: {
                            currency: 'AUD',
                            value: 7,
                            __typename: 'Money',
                        },
                        regular_price: {
                            currency: 'AUD',
                            value: 7,
                            __typename: 'Money',
                        },
                        __typename: 'ProductPrice',
                    },
                    __typename: 'PriceRange',
                },
                custom_attributes: [],
                rating_summary: 0,
                review_count: 0,
                reviews: [],
                staged: false,
                uid: 'OA==',
                redirect_code: 0,
                __typename: 'SimpleProduct',
            },
        ],
        redirect_code: 0,
        reviews: [],
        sku: 'WH01',
        small_image: {
            url: 'https://take-flight-ew3k5nq-ekxw7lyelhava.ap-4.magentosite.cloud/media/catalog/product/cache/8f3d2e129ba9bc6369f4f94872c5b9a2/w/h/wh01-green_main.jpg',
            __typename: 'ProductImage',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'afdgagr',
        url_key: 'mona-pullover-hoodlie',
        url_suffix: '.html',
        configurable_options: [
            {
                attribute_code: 'color',
                attribute_id: '93',
                attribute_uid: 'sdf',
                id: 147,
                label: 'Color',
                position: 1,
                uid: 'fdgf',
                values: [
                    {
                        default_label: 'Green',
                        label: 'Green',
                        store_label: 'Green',
                        use_default_value: true,
                        value_index: 62,
                        swatch_data: {
                            value: '#53a828',
                            __typename: 'ColorSwatchData',
                        },
                        uid: 'Y29uZmlndXJhYmxlLzkzLzYy',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                    {
                        default_label: 'Purple',
                        label: 'Purple',
                        store_label: 'Purple',
                        use_default_value: true,
                        value_index: 66,
                        swatch_data: {
                            value: '#ef3dff',
                            __typename: 'ColorSwatchData',
                        },
                        uid: 'Y29uZmlndXJhYmxlLzkzLzY2',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                ],
                __typename: 'ConfigurableProductOptions',
            },
            {
                attribute_code: 'size',
                attribute_id: '187',
                attribute_uid: 'sdf',
                id: 146,
                label: 'Size',
                position: 0,
                uid: 'fdgf',
                values: [
                    {
                        default_label: 'S',
                        label: 'S',
                        store_label: 'S',
                        use_default_value: true,
                        value_index: 180,
                        swatch_data: {
                            value: 'S',
                            __typename: 'TextSwatchData',
                        },
                        uid: 'Y29uZmlndXJhYmxlLzE4Ny8xODA=',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                    {
                        default_label: 'M',
                        label: 'M',
                        store_label: 'M',
                        use_default_value: true,
                        value_index: 181,
                        swatch_data: {
                            value: 'M',
                            __typename: 'TextSwatchData',
                        },
                        uid: 'Y29uZmlndXJhYmxlLzE4Ny8xODE=',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                ],
                __typename: 'ConfigurableProductOptions',
            },
        ],
        variants: [
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 62,
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 180,
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1034,
                    media_gallery_entries: [
                        {
                            id: 1742,
                            disabled: false,
                            file: '/w/h/wh01-green_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1743,
                            disabled: false,
                            file: '/w/h/wh01-green_alt1.jpg',
                            label: '',
                            position: 2,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1744,
                            disabled: false,
                            file: '/w/h/wh01-green_back.jpg',
                            label: '',
                            position: 3,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    staged: false,
                    sku: 'WH01-S-Green',
                    stock_status: 'IN_STOCK',
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 27,
                                percent_off: 47.37,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 30,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    __typename: 'SimpleProduct',
                },
                custom_attributes: [],
                rating_summary: 0,
                review_count: 0,
                reviews: [],
                staged: false,
                uid: 'OA==',
                redirect_code: 0,
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 66,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 180,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1036,
                    media_gallery_entries: [
                        {
                            id: 1746,
                            disabled: false,
                            file: '/w/h/wh01-purple_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    sku: 'WH01-S-Purple',
                    staged: false,
                    stock_status: 'IN_STOCK',
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 62,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 181,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1037,
                    media_gallery_entries: [
                        {
                            id: 1747,
                            disabled: false,
                            file: '/w/h/wh01-green_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1748,
                            disabled: false,
                            file: '/w/h/wh01-green_alt1.jpg',
                            label: '',
                            position: 2,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1749,
                            disabled: false,
                            file: '/w/h/wh01-green_back.jpg',
                            label: '',
                            position: 3,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    sku: 'WH01-M-Green',
                    staged: false,
                    stock_status: 'IN_STOCK',
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 66,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 181,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1039,
                    media_gallery_entries: [
                        {
                            id: 1751,
                            disabled: false,
                            file: '/w/h/wh01-purple_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    sku: 'WH01-M-Purple',
                    staged: false,
                    stock_status: 'IN_STOCK',
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
        ],
    },
    {
        id: 1034,
        media_gallery_entries: [
            {
                id: 1742,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1743,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                label: '',
                position: 2,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1744,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                label: '',
                position: 3,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        staged: false,
        sku: 'WH01-S-Green',
        stock_status: 'IN_STOCK',
        price_range: {
            minimum_price: {
                discount: {
                    amount_off: 27,
                    percent_off: 47.37,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 30,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        __typename: 'SimpleProduct',
    },
    {
        id: 1036,
        media_gallery_entries: [
            {
                id: 1746,
                disabled: false,
                file: '/w/h/wh01-purple_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        sku: 'WH01-S-Purple',
        staged: false,
        stock_status: 'IN_STOCK',
        price_range: {
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
    {
        id: 1037,
        media_gallery_entries: [
            {
                id: 1747,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1748,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                label: '',
                position: 2,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1749,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                label: '',
                position: 3,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        sku: 'WH01-M-Green',
        staged: false,
        stock_status: 'IN_STOCK',
        price_range: {
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
    {
        id: 1039,
        media_gallery_entries: [
            {
                id: 1751,
                disabled: false,
                file: '/w/h/wh01-purple_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        sku: 'WH01-M-Purple',
        staged: false,
        stock_status: 'IN_STOCK',
        price_range: {
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                    __typename: 'ProductDiscount',
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                    __typename: 'Money',
                },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
];

describe('products', () => {
    it('Flattens variants as separate array items', () => {
        expect(
            getDeNestedProductVariants(productsMock as { items: Array<ConfigurableProduct> })
        ).toEqual(expectResult);
    });

    it('Returns an empty array if there are no products', () => {
        expect(getDeNestedProductVariants(null)).toEqual([]);
        expect(getDeNestedProductVariants({ items: [null] })).toEqual([]);
    });
});
