import { mockBcCart } from '../../../resolvers/mocks/cart.bc';
import { getTransformCartItems } from '../transform-cart-items';
import { ProductInterface } from '@aligent/bigcommerce-resolvers';
import { CurrencyEnum, ProductReviews, ProductStockStatus } from '@aligent/bigcommerce-resolvers';

export const mockFlattenedProducts = [
    {
        __typename: 'ConfigurableProduct',
        categories: [
            {
                uid: 'OA==',
                breadcrumbs: null,
                name: 'New Luma Yoga Collection',
                level: 3,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjE=',
                breadcrumbs: null,
                name: 'Women',
                level: 2,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjI=',
                breadcrumbs: [
                    { category_uid: 'MjE=', category_name: 'Women', __typename: 'Breadcrumb' },
                ],
                name: 'Tops',
                level: 3,
                staged: false,
                redirect_code: 0,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MjU=',
                breadcrumbs: [
                    { category_uid: 'MjE=', category_name: 'Women', __typename: 'Breadcrumb' },
                    { category_uid: 'MjI=', category_name: 'Tops', __typename: 'Breadcrumb' },
                ],
                name: 'Hoodies & Sweatshirts',
                level: 4,
                redirect_code: 0,
                staged: false,
                __typename: 'CategoryTree',
            },
            {
                uid: 'MzU=',
                breadcrumbs: null,
                name: 'Erin Recommends',
                level: 3,
                redirect_code: 0,
                staged: false,
                __typename: 'CategoryTree',
            },
        ],
        custom_attributes: [],
        description: {
            html: "Whether you're after energizing activity or eye-catching apparel, the Mona Pullover is what you want. You'll stay warm and look fashionable, wherever you are.<br /> <br /> &bull; Light green heathered hoodie. <br /> &bull; Long-Sleeve, pullover.<br /> &bull; Long elliptical hem for extra coverage.<br /> &bull; Deep button placket for layering.<br /> &bull; Double rib design.<br /> &bull; Mid layer, mid weight.<br /> &bull; 98% Merino Wool / 2% Spandex",
            __typename: 'ComplexTextValue',
        },
        id: 1046,
        media_gallery_entries: [
            {
                id: 1762,
                label: '',
                position: 1,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1763,
                label: '',
                position: 2,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1764,
                label: '',
                position: 3,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        meta_title: null,
        meta_keyword: null,
        meta_description: null,
        name: 'Mona Pullover Hoodlie',
        price: {
            regularPrice: {
                amount: { currency: 'AUD' as CurrencyEnum, value: 55, __typename: 'Money' },
                __typename: 'Price',
            },
            __typename: 'ProductPrices',
        },
        price_range: {
            maximum_price: {
                discount: { amount_off: 0, percent_off: 0, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            minimum_price: {
                discount: { amount_off: 25, percent_off: 45.45, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 30, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 55, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        price_tiers: [],
        rating_summary: 87,
        review_count: 3,
        related_products: [
            {
                categories: [],
                name: 'Affirm Water Bottle ',
                id: 15,
                sku: '24-UG06',
                url_key: 'affirm-water-bottle',
                url_suffix: '.html',
                small_image: {
                    url: 'https://take-flight-ew3k5nq-ekxw7lyelhava.ap-4.magentosite.cloud/media/catalog/product/cache/8f3d2e129ba9bc6369f4f94872c5b9a2/u/g/ug06-lb-0.jpg',
                    __typename: 'ProductImage',
                },
                price: {
                    regularPrice: {
                        amount: { currency: 'AUD' as CurrencyEnum, value: 7, __typename: 'Money' },
                        __typename: 'Price',
                    },
                    __typename: 'ProductPrices',
                },
                price_range: {
                    minimum_price: {
                        discount: { amount_off: 0, __typename: 'ProductDiscount' },
                        final_price: {
                            currency: 'AUD' as CurrencyEnum,
                            value: 7,
                            __typename: 'Money',
                        },
                        regular_price: {
                            currency: 'AUD' as CurrencyEnum,
                            value: 7,
                            __typename: 'Money',
                        },
                        __typename: 'ProductPrice',
                    },
                    __typename: 'PriceRange',
                },
                custom_attributes: [],
                rating_summary: 0,
                review_count: 0,
                reviews: [] as unknown as ProductReviews,
                staged: false,
                uid: 'OA==',
                redirect_code: 0,
                only_x_left_in_stock: 11,
                __typename: 'SimpleProduct',
            },
        ],
        redirect_code: 0,
        reviews: [] as unknown as ProductReviews,
        sku: 'WH01',
        small_image: {
            url: 'https://take-flight-ew3k5nq-ekxw7lyelhava.ap-4.magentosite.cloud/media/catalog/product/cache/8f3d2e129ba9bc6369f4f94872c5b9a2/w/h/wh01-green_main.jpg',
            __typename: 'ProductImage',
        },
        staged: false,
        stock_status: 'IN_STOCK' as ProductStockStatus,
        uid: 'afdgagr',
        url_key: 'mona-pullover-hoodlie',
        url_suffix: '.html',
        configurable_options: [
            {
                attribute_code: 'color',
                attribute_id: '93',
                attribute_uid: 'sdf',
                id: 147,
                label: 'Color',
                position: 1,
                uid: 'fdgf',
                values: [
                    {
                        default_label: 'Green',
                        label: 'Green',
                        store_label: 'Green',
                        use_default_value: true,
                        value_index: 62,
                        swatch_data: { value: '#53a828', __typename: 'ColorSwatchData' },
                        uid: 'Y29uZmlndXJhYmxlLzkzLzYy',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                    {
                        default_label: 'Purple',
                        label: 'Purple',
                        store_label: 'Purple',
                        use_default_value: true,
                        value_index: 66,
                        swatch_data: { value: '#ef3dff', __typename: 'ColorSwatchData' },
                        uid: 'Y29uZmlndXJhYmxlLzkzLzY2',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                ],
                __typename: 'ConfigurableProductOptions',
            },
            {
                attribute_code: 'size',
                attribute_id: '187',
                attribute_uid: 'sdf',
                id: 146,
                label: 'Size',
                position: 0,
                uid: 'fdgf',
                values: [
                    {
                        default_label: 'S',
                        label: 'S',
                        store_label: 'S',
                        use_default_value: true,
                        value_index: 180,
                        swatch_data: { value: 'S', __typename: 'TextSwatchData' },
                        uid: 'Y29uZmlndXJhYmxlLzE4Ny8xODA=',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                    {
                        default_label: 'M',
                        label: 'M',
                        store_label: 'M',
                        use_default_value: true,
                        value_index: 181,
                        swatch_data: { value: 'M', __typename: 'TextSwatchData' },
                        uid: 'Y29uZmlndXJhYmxlLzE4Ny8xODE=',
                        __typename: 'ConfigurableProductOptionsValues',
                    },
                ],
                __typename: 'ConfigurableProductOptions',
            },
        ],
        variants: [
            {
                attributes: [
                    { code: 'color', value_index: 62, __typename: 'ConfigurableAttributeOption' },
                    { code: 'size', value_index: 180, __typename: 'ConfigurableAttributeOption' },
                ],
                product: {
                    id: 1034,
                    media_gallery_entries: [
                        {
                            id: 1742,
                            disabled: false,
                            file: '/w/h/wh01-green_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1743,
                            disabled: false,
                            file: '/w/h/wh01-green_alt1.jpg',
                            label: '',
                            position: 2,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1744,
                            disabled: false,
                            file: '/w/h/wh01-green_back.jpg',
                            label: '',
                            position: 3,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    only_x_left_in_stock: 11,
                    staged: false,
                    sku: 'WH01-S-Green',
                    stock_status: 'IN_STOCK' as ProductStockStatus,
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 27,
                                percent_off: 47.37,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 30,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    __typename: 'SimpleProduct',
                },
                custom_attributes: [],
                rating_summary: 0,
                review_count: 0,
                reviews: [],
                staged: false,
                uid: 'OA==',
                redirect_code: 0,
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 66,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 180,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1036,
                    media_gallery_entries: [
                        {
                            id: 1746,
                            disabled: false,
                            file: '/w/h/wh01-purple_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    only_x_left_in_stock: 11,
                    sku: 'WH01-S-Purple',
                    staged: false,
                    stock_status: 'IN_STOCK' as ProductStockStatus,
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 62,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 181,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1037,
                    media_gallery_entries: [
                        {
                            id: 1747,
                            disabled: false,
                            file: '/w/h/wh01-green_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1748,
                            disabled: false,
                            file: '/w/h/wh01-green_alt1.jpg',
                            label: '',
                            position: 2,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                        {
                            id: 1749,
                            disabled: false,
                            file: '/w/h/wh01-green_back.jpg',
                            label: '',
                            position: 3,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    only_x_left_in_stock: 11,
                    sku: 'WH01-M-Green',
                    staged: false,
                    stock_status: 'IN_STOCK' as ProductStockStatus,
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
            {
                attributes: [
                    {
                        code: 'color',
                        value_index: 66,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                    {
                        code: 'size',
                        value_index: 181,
                        uid: 'asdf',
                        __typename: 'ConfigurableAttributeOption',
                    },
                ],
                product: {
                    id: 1039,
                    media_gallery_entries: [
                        {
                            id: 1751,
                            disabled: false,
                            file: '/w/h/wh01-purple_main.jpg',
                            label: '',
                            position: 1,
                            uid: 'OA==',
                            __typename: 'MediaGalleryEntry',
                        },
                    ],
                    only_x_left_in_stock: 11,
                    sku: 'WH01-M-Purple',
                    staged: false,
                    stock_status: 'IN_STOCK' as ProductStockStatus,
                    price_range: {
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                                __typename: 'ProductDiscount',
                            },
                            final_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            regular_price: {
                                currency: 'AUD' as CurrencyEnum,
                                value: 57,
                                __typename: 'Money',
                            },
                            __typename: 'ProductPrice',
                        },
                        __typename: 'PriceRange',
                    },
                    custom_attributes: [],
                    rating_summary: 0,
                    review_count: 0,
                    reviews: [],
                    uid: 'OA==',
                    redirect_code: 0,
                    __typename: 'SimpleProduct',
                },
                __typename: 'ConfigurableVariant',
            },
        ],
    },
    {
        id: 1034,
        media_gallery_entries: [
            {
                id: 1742,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1743,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                label: '',
                position: 2,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1744,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                label: '',
                position: 3,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        only_x_left_in_stock: 11,
        staged: false,
        sku: 'WH01-S-Green',
        stock_status: 'IN_STOCK' as ProductStockStatus,
        price_range: {
            minimum_price: {
                discount: { amount_off: 27, percent_off: 47.37, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 30, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        __typename: 'SimpleProduct',
    },
    {
        id: 1036,
        media_gallery_entries: [
            {
                id: 1746,
                disabled: false,
                file: '/w/h/wh01-purple_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        only_x_left_in_stock: 11,
        sku: 'WH01-S-Purple',
        staged: false,
        stock_status: 'IN_STOCK' as ProductStockStatus,
        price_range: {
            minimum_price: {
                discount: { amount_off: 0, percent_off: 0, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
    {
        id: 1037,
        media_gallery_entries: [
            {
                id: 1747,
                disabled: false,
                file: '/w/h/wh01-green_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1748,
                disabled: false,
                file: '/w/h/wh01-green_alt1.jpg',
                label: '',
                position: 2,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
            {
                id: 1749,
                disabled: false,
                file: '/w/h/wh01-green_back.jpg',
                label: '',
                position: 3,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        only_x_left_in_stock: 11,
        sku: 'WH01-M-Green',
        staged: false,
        stock_status: 'IN_STOCK' as ProductStockStatus,
        price_range: {
            minimum_price: {
                discount: { amount_off: 0, percent_off: 0, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
    {
        id: 1039,
        media_gallery_entries: [
            {
                id: 1751,
                disabled: false,
                file: '/w/h/wh01-purple_main.jpg',
                label: '',
                position: 1,
                uid: 'OA==',
                __typename: 'MediaGalleryEntry',
            },
        ],
        only_x_left_in_stock: 11,
        sku: 'WH01-M-Purple',
        staged: false,
        stock_status: 'IN_STOCK' as ProductStockStatus,
        price_range: {
            minimum_price: {
                discount: { amount_off: 0, percent_off: 0, __typename: 'ProductDiscount' },
                final_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                regular_price: { currency: 'AUD' as CurrencyEnum, value: 57, __typename: 'Money' },
                __typename: 'ProductPrice',
            },
            __typename: 'PriceRange',
        },
        custom_attributes: [],
        rating_summary: 0,
        review_count: 0,
        reviews: [],
        uid: 'OA==',
        redirect_code: 0,
        __typename: 'SimpleProduct',
    },
];

const expectResult = [
    {
        id: 'df21b1d0-6178-454c-a159-699e80c7d8e0',
        uid: 'ZGYyMWIxZDAtNjE3OC00NTRjLWExNTktNjk5ZTgwYzdkOGUwLzQ5Mi81MTM=',
        errors: null,
        prices: {
            price: { currency: 'AUD', value: 30 },
            price_including_tax: { currency: 'AUD', value: 30 },
            row_total: { currency: 'AUD', value: 60 },
            row_total_including_tax: { currency: 'AUD', value: 60 },
            total_item_discount: { currency: 'AUD', value: 0 },
        },
        product: {
            id: 1034,
            uid: 'NTEz',
            name: 'Mona Pullover Hoodlie',
            media_gallery_entries: [
                {
                    id: 1742,
                    disabled: false,
                    file: '/w/h/wh01-green_main.jpg',
                    label: '',
                    position: 1,
                    uid: 'OA==',
                    __typename: 'MediaGalleryEntry',
                },
                {
                    id: 1743,
                    disabled: false,
                    file: '/w/h/wh01-green_alt1.jpg',
                    label: '',
                    position: 2,
                    uid: 'OA==',
                    __typename: 'MediaGalleryEntry',
                },
                {
                    id: 1744,
                    disabled: false,
                    file: '/w/h/wh01-green_back.jpg',
                    label: '',
                    position: 3,
                    uid: 'OA==',
                    __typename: 'MediaGalleryEntry',
                },
            ],
            only_x_left_in_stock: 11,
            sku: 'WH01-S-Green',
            small_image: {
                url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/product_images/attribute_rule_images/54_thumb_1690452039.jpg',
                label: 'Mona Pullover Hoodlie',
            },
            categories: [],
            stock_status: 'IN_STOCK',
            price_range: {
                minimum_price: {
                    discount: { amount_off: 40 },
                    final_price: { currency: 'AUD', value: 30 },
                    regular_price: { currency: 'AUD', value: 70 },
                },
            },
            rating_summary: 0,
            review_count: 0,
            url_key: 'mona-pullover-hoodlie',
            url_suffix: '',
            custom_attributes: [],
            reviews: {
                items: [],
                page_info: { current_page: null, page_size: null, total_pages: null },
            },
            staged: false,
            __typename: 'SimpleProduct',
        },
        quantity: 2,
        configurable_options: [
            { id: 148, option_label: 'Color', value_id: 182, value_label: 'Green' },
            { id: 149, option_label: 'Size', value_id: 184, value_label: 'S' },
        ],
        __typename: 'ConfigurableCartItem',
    },
];

describe('transform-cart-items', () => {
    it(`transforms cart item`, () => {
        expect(
            getTransformCartItems(mockBcCart, mockFlattenedProducts as Array<ProductInterface>)
        ).toEqual(expect.objectContaining(expectResult));
    });

    it(`returns "null" if there's no cart`, () => {
        expect(getTransformCartItems(null)).toEqual(expect.objectContaining(null));
    });
});
