import { BCOrder } from '../../../../types';
import { CustomerOrders } from '@aligent/bigcommerce-resolvers';

export const bcOrders: BCOrder[] = [
    {
        id: 130,
        customer_id: 18,
        date_created: 'Tue, 29 Aug 2023 02:26:57 +0000',
        date_modified: 'Tue, 29 Aug 2023 02:26:58 +0000',
        date_shipped: '',
        status_id: 7,
        status: 'Awaiting Payment',
        subtotal_ex_tax: '56.9200',
        subtotal_inc_tax: '62.6200',
        subtotal_tax: '5.7000',
        base_shipping_cost: '0.0000',
        shipping_cost_ex_tax: '0.0000',
        shipping_cost_inc_tax: '0.0000',
        shipping_cost_tax: '0.0000',
        shipping_cost_tax_class_id: 2,
        base_handling_cost: '0.0000',
        handling_cost_ex_tax: '0.0000',
        handling_cost_inc_tax: '0.0000',
        handling_cost_tax: '0.0000',
        handling_cost_tax_class_id: 2,
        base_wrapping_cost: '0.0000',
        wrapping_cost_ex_tax: '0.0000',
        wrapping_cost_inc_tax: '0.0000',
        wrapping_cost_tax: '0.0000',
        wrapping_cost_tax_class_id: 3,
        total_ex_tax: '56.9200',
        total_inc_tax: '62.6200',
        total_tax: '5.7000',
        items_total: 4,
        items_shipped: 0,
        payment_method: 'Bank Deposit',
        payment_provider_id: 'payment Id',
        payment_status: '',
        refunded_amount: '0.0000',
        order_is_digital: false,
        store_credit_amount: '0.0000',
        gift_certificate_amount: '0.0000',
        ip_address: '60.241.250.29',
        ip_address_v6: '',
        geoip_country: 'Australia',
        geoip_country_iso2: 'AU',
        currency_id: 1,
        currency_code: 'AUD',
        currency_exchange_rate: '1.0000000000',
        default_currency_id: 1,
        default_currency_code: 'AUD',
        staff_notes: '',
        customer_message: '',
        discount_amount: '0.0000',
        coupon_discount: '0.0000',
        shipping_address_count: 1,
        is_deleted: false,
        ebay_order_id: '0',
        cart_id: '0fbafd16-5472-4f50-80ed-dda85b01072a',
        billing_address: {
            first_name: 'jack',
            last_name: 'mcloughlin',
            company: '',
            street_1: '212 pirie st',
            street_2: 'Level 1',
            city: 'Adelaide',
            state: 'South Australia',
            zip: '5000',
            country: 'Australia',
            country_iso2: 'AU',
            phone: '0432471111',
            email: 'jack.mcloughlin+mesh@aligent.com.au',
            form_fields: [
                { name: 'Comments', value: '' },
                {
                    name: 'Authority To Leave',
                    value: ['Yes - Allow my order to be delivered without requiring a signature'],
                },
                { name: 'Default Billing', value: ['Yes'] },
                { name: 'Default Shipping', value: [] },
            ],
        },
        is_email_opt_in: false,
        credit_card_type: null,
        order_source: 'www',
        channel_id: 1,
        external_source: '',
        consignments: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/130/consignments',
            resource: '/orders/130/consignments',
        },
        products: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/130/products',
            resource: '/orders/130/products',
        },
        shipping_addresses: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/130/shipping_addresses',
            resource: '/orders/130/shipping_addresses',
        },
        coupons: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/130/coupons',
            resource: '/orders/130/coupons',
        },
        external_id: null,
        external_merchant_id: null,
        tax_provider_id: 'BasicTaxProvider',
        customer_locale: 'en',
        external_order_id: '',
        store_default_currency_code: 'AUD',
        store_default_to_transactional_exchange_rate: '1.0000000000',
        custom_status: 'Awaiting Payment',
    },
    {
        id: 129,
        customer_id: 18,
        date_created: 'Tue, 29 Aug 2023 02:22:35 +0000',
        date_modified: 'Tue, 29 Aug 2023 02:23:09 +0000',
        date_shipped: 'Tue, 29 Aug 2023 02:23:09 +0000',
        status_id: 10,
        status: 'Completed',
        subtotal_ex_tax: '334.5500',
        subtotal_inc_tax: '368.0000',
        subtotal_tax: '33.4500',
        base_shipping_cost: '0.0000',
        shipping_cost_ex_tax: '0.0000',
        shipping_cost_inc_tax: '0.0000',
        shipping_cost_tax: '0.0000',
        shipping_cost_tax_class_id: 2,
        base_handling_cost: '0.0000',
        handling_cost_ex_tax: '0.0000',
        handling_cost_inc_tax: '0.0000',
        handling_cost_tax: '0.0000',
        handling_cost_tax_class_id: 2,
        base_wrapping_cost: '0.0000',
        wrapping_cost_ex_tax: '0.0000',
        wrapping_cost_inc_tax: '0.0000',
        wrapping_cost_tax: '0.0000',
        wrapping_cost_tax_class_id: 3,
        total_ex_tax: '334.5500',
        total_inc_tax: '368.0000',
        total_tax: '33.4500',
        items_total: 1,
        items_shipped: 0,
        payment_method: 'Bank Deposit',
        payment_provider_id: 'payment Id',
        payment_status: 'pending',
        refunded_amount: '0.0000',
        order_is_digital: false,
        store_credit_amount: '0.0000',
        gift_certificate_amount: '0.0000',
        ip_address: '60.241.250.29',
        ip_address_v6: '',
        geoip_country: 'Australia',
        geoip_country_iso2: 'AU',
        currency_id: 1,
        currency_code: 'AUD',
        currency_exchange_rate: '1.0000000000',
        default_currency_id: 1,
        default_currency_code: 'AUD',
        staff_notes: '',
        customer_message: '',
        discount_amount: '0.0000',
        coupon_discount: '0.0000',
        shipping_address_count: 1,
        is_deleted: false,
        ebay_order_id: '0',
        cart_id: '632802f1-8f2a-4d44-b857-12de988277da',
        billing_address: {
            first_name: 'jack',
            last_name: 'mcloughlin',
            company: '',
            street_1: '212 pirie st',
            street_2: 'Level 1',
            city: 'Adelaide',
            state: 'South Australia',
            zip: '5000',
            country: 'Australia',
            country_iso2: 'AU',
            phone: '0432471111',
            email: 'jack.mcloughlin+mesh@aligent.com.au',
            form_fields: [
                { name: 'Comments', value: '' },
                {
                    name: 'Authority To Leave',
                    value: ['Yes - Allow my order to be delivered without requiring a signature'],
                },
                { name: 'Default Billing', value: ['Yes'] },
                { name: 'Default Shipping', value: [] },
            ],
        },
        is_email_opt_in: false,
        credit_card_type: null,
        order_source: 'manual',
        channel_id: 1,
        external_source: '',
        consignments: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/129/consignments',
            resource: '/orders/129/consignments',
        },
        products: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/129/products',
            resource: '/orders/129/products',
        },
        shipping_addresses: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/129/shipping_addresses',
            resource: '/orders/129/shipping_addresses',
        },
        coupons: {
            url: 'https://api.bigcommerce.com/stores/xxazhvt7gd/v2/orders/129/coupons',
            resource: '/orders/129/coupons',
        },
        external_id: null,
        external_merchant_id: null,
        tax_provider_id: 'BasicTaxProvider',
        customer_locale: 'en',
        external_order_id: '',
        store_default_currency_code: 'AUD',
        store_default_to_transactional_exchange_rate: '1.0000000000',
        custom_status: 'Completed',
    },
];

export const acOrders: CustomerOrders = {
    items: [
        {
            billing_address: {
                city: 'Adelaide',
                company: '',
                country_code: 'AU',
                firstname: 'jack',
                lastname: 'mcloughlin',
                postcode: '5000',
                street: ['212 pirie st Level 1'],
                telephone: '0432471111',
                region: 'South Australia',
            },
            number: '130',
            id: 'MTMw',
            order_date: '2023-08-29 02:26:57',
            status: 'Awaiting Payment',
            total: {
                grand_total: { currency: 'AUD', value: 62.62 },
                base_grand_total: { currency: 'AUD', value: null },
                discounts: [],
                shipping_handling: {
                    amount_including_tax: {
                        currency: 'AUD',
                        value: 0,
                    },
                    total_amount: { currency: 'AUD', value: 62.62 },
                },
                subtotal: { currency: 'AUD', value: 62.62 },
                subtotal_incl_tax: {
                    currency: 'AUD',
                    value: 62.62,
                },
                taxes: [
                    {
                        amount: {
                            currency: 'AUD',
                            value: 5.7,
                        },
                        rate: 10,
                        title: 'GST',
                    },
                ],
                total_giftcard: {
                    currency: 'AUD',
                    value: 0,
                },
                total_shipping: { currency: 'AUD', value: 0 },
                total_tax: { currency: 'AUD', value: 5.7 },
            },
            gift_receipt_included: false,
            order_number: '130',
            payment_methods: [
                {
                    additional_data: null,
                    name: 'Bank Deposit',
                    type: 'Bank Deposit',
                },
            ],
            printed_card_included: false,
            state: '7',
            invoices: [],
            currency_code: 'AUD',
        },
        {
            billing_address: {
                city: 'Adelaide',
                company: '',
                country_code: 'AU',
                firstname: 'jack',
                lastname: 'mcloughlin',
                postcode: '5000',
                region: 'South Australia',
                street: ['212 pirie st Level 1'],
                telephone: '0432471111',
            },
            currency_code: 'AUD',
            gift_receipt_included: false,
            id: 'MTI5',
            invoices: [],
            number: '129',
            order_date: '2023-08-29 02:22:35',
            order_number: '129',
            payment_methods: [
                {
                    additional_data: null,
                    name: 'Bank Deposit',
                    type: 'Bank Deposit',
                },
            ],
            printed_card_included: false,
            state: '10',
            status: 'Completed',
            total: {
                base_grand_total: {
                    currency: 'AUD',
                    value: null,
                },
                discounts: [],
                grand_total: {
                    currency: 'AUD',
                    value: 368,
                },
                shipping_handling: {
                    amount_including_tax: {
                        currency: 'AUD',
                        value: 0,
                    },
                    total_amount: {
                        currency: 'AUD',
                        value: 368,
                    },
                },
                subtotal: {
                    currency: 'AUD',
                    value: 368,
                },
                subtotal_incl_tax: {
                    currency: 'AUD',
                    value: 368,
                },
                taxes: [
                    {
                        amount: {
                            currency: 'AUD',
                            value: 33.45,
                        },
                        rate: 10,
                        title: 'GST',
                    },
                ],
                total_giftcard: {
                    currency: 'AUD',
                    value: 0,
                },
                total_shipping: {
                    currency: 'AUD',
                    value: 0,
                },
                total_tax: {
                    currency: 'AUD',
                    value: 33.45,
                },
            },
        },
    ],
    page_info: {
        current_page: 1,
        page_size: 20,
        total_pages: 1,
    },
    total_count: 2,
};
