export const mockFlattenedProducts = [
    {
        brand: 'Weller',
        categories: [
            {
                canonical_url: 'shop-all',
                children: [],
                children_count: '0',
                description: '',
                id: 23,
                include_in_menu: 1,
                level: 1,
                meta_description: '',
                meta_title: '',
                name: 'Shop All',
                path: '0/23',
                position: 0,
                products: null,
                redirect_code: 0,
                uid: 'MjM=',
                url_path: 'shop-all',
                url_suffix: '',
                staged: false,
                breadcrumbs: [],
                __typename: 'CategoryTree',
            },
            {
                canonical_url: 'whats-new',
                children: [],
                children_count: '0',
                description: '',
                id: 57,
                include_in_menu: 1,
                level: 1,
                meta_description: 'This is the "What\'s New" meta_description',
                meta_title: "What's New",
                name: "What's New",
                path: '0/57',
                position: 0,
                products: null,
                redirect_code: 0,
                uid: 'NTc=',
                url_path: 'whats-new',
                url_suffix: '',
                staged: false,
                breadcrumbs: [],
                __typename: 'CategoryTree',
            },
            {
                canonical_url: 'women',
                children: [],
                children_count: '0',
                description: '',
                id: 58,
                include_in_menu: 1,
                level: 1,
                meta_description: 'This is the "Women" meta_description',
                meta_title: 'Women',
                name: 'Women',
                path: '0/58',
                position: 0,
                products: null,
                redirect_code: 0,
                uid: 'NTg=',
                url_path: 'women',
                url_suffix: '',
                staged: false,
                breadcrumbs: [],
                __typename: 'CategoryTree',
                is_women_category: 'true',
            },
            {
                canonical_url: 'women/tops',
                children: [],
                children_count: '0',
                description: '',
                id: 59,
                include_in_menu: 1,
                level: 2,
                meta_description: '',
                meta_title: '',
                name: 'Tops',
                path: '0/59',
                position: 0,
                products: null,
                redirect_code: 0,
                uid: 'NTk=',
                url_path: 'women/tops',
                url_suffix: '',
                staged: false,
                breadcrumbs: [
                    {
                        category_id: 58,
                        category_level: 1,
                        category_name: 'Women',
                        category_url_path: 'women',
                        category_url_key: 'women',
                        category_uid: 'NTg=',
                    },
                ],
                __typename: 'CategoryTree',
            },
            {
                canonical_url: 'women/tops/hoodies-sweatshirts',
                children: [],
                children_count: '0',
                description: '',
                id: 60,
                include_in_menu: 1,
                level: 3,
                meta_description: '',
                meta_title: '',
                name: 'Hoodies & Sweatshirts',
                path: '0/60',
                position: 0,
                products: null,
                redirect_code: 0,
                uid: 'NjA=',
                url_path: 'women/tops/hoodies-sweatshirts',
                url_suffix: '',
                staged: false,
                breadcrumbs: [
                    {
                        category_id: 58,
                        category_level: 1,
                        category_name: 'Women',
                        category_url_path: 'women',
                        category_url_key: 'women',
                        category_uid: 'NTg=',
                    },
                    {
                        category_id: 59,
                        category_level: 2,
                        category_name: 'Tops',
                        category_url_path: 'women/tops',
                        category_url_key: 'women/tops',
                        category_uid: 'NTk=',
                    },
                ],
                __typename: 'CategoryTree',
            },
        ],
        configurable_options: [
            {
                attribute_code: 'color',
                attribute_id: '148',
                displayStyle: 'Swatch',
                id: 148,
                label: 'Color',
                values: [
                    {
                        __typename: 'ConfigurableProductOptionsValues',
                        default_label: 'Green',
                        label: 'Green',
                        store_label: 'Green',
                        use_default_value: false,
                        value_index: 182,
                        uid: 'Y29uZmlndXJhYmxlLzE0OC8xODI=',
                        swatch_data: {
                            value: '#334B28',
                            __typename: 'ColorSwatchData',
                        },
                    },
                    {
                        __typename: 'ConfigurableProductOptionsValues',
                        default_label: 'Purple',
                        label: 'Purple',
                        store_label: 'Purple',
                        use_default_value: true,
                        value_index: 183,
                        uid: 'Y29uZmlndXJhYmxlLzE0OC8xODM=',
                        swatch_data: {
                            value: '#EF3DFF',
                            __typename: 'ColorSwatchData',
                        },
                    },
                    {
                        __typename: 'ConfigurableProductOptionsValues',
                        default_label: 'Light Blue',
                        label: 'Light Blue',
                        store_label: 'Light Blue',
                        use_default_value: false,
                        value_index: 236,
                        uid: 'Y29uZmlndXJhYmxlLzE0OC8yMzY=',
                        swatch_data: {
                            value: '#A0DEF2',
                            __typename: 'ColorSwatchData',
                        },
                    },
                ],
                attribute_uid: 'MTQ4',
                uid: 'MTQ4',
            },
            {
                attribute_code: 'size',
                attribute_id: '149',
                displayStyle: 'RadioButtons',
                id: 149,
                label: 'Size',
                values: [
                    {
                        __typename: 'ConfigurableProductOptionsValues',
                        default_label: 'S',
                        label: 'S',
                        store_label: 'S',
                        use_default_value: false,
                        value_index: 184,
                        uid: 'Y29uZmlndXJhYmxlLzE0OS8xODQ=',
                    },
                    {
                        __typename: 'ConfigurableProductOptionsValues',
                        default_label: 'M',
                        label: 'M',
                        store_label: 'M',
                        use_default_value: false,
                        value_index: 185,
                        uid: 'Y29uZmlndXJhYmxlLzE0OS8xODU=',
                    },
                ],
                attribute_uid: 'MTQ5',
                uid: 'MTQ5',
            },
        ],
        description: {
            html: "<p>Whether you're after energizing activity or eye-catching apparel, the Mona Pullover is what you want. You'll stay warm and look fashionable, wherever you are.&lt;br /&gt; &lt;br /&gt; &amp;bull; Light green heathered hoodie. &lt;br /&gt; &amp;bull; Long-Sleeve, pullover.&lt;br /&gt; &amp;bull; Long elliptical hem for extra coverage.&lt;br /&gt; &amp;bull; Deep button placket for layering.&lt;br /&gt; &amp;bull; Double rib design.&lt;br /&gt; &amp;bull; Mid layer, mid weight.&lt;br /&gt; &amp;bull; 98% Merino Wool / 2% Spandex</p>",
        },
        staged: true,
        uid: 'UHJvZHVjdDo0OTI=',
        custom_attributes: [],
        id: 492,
        items: [],
        media_gallery_entries: [
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/products/492/401/wh01-green_main__96543.1690452070.jpg',
                id: 12573090,
                label: '',
                position: 0,
                uid: '',
            },
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/products/492/402/wh01-purple_main__43854.1690452461.jpg',
                id: 13020129,
                label: '',
                position: 1,
                uid: '',
            },
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/products/492/412/woman__46527.1698882973.jpg',
                id: 15004501,
                label: '',
                position: 2,
                uid: '',
            },
        ],
        meta_title: 'Mona Pullover Hoodlie',
        meta_keyword: '',
        meta_description: '',
        name: 'Mona Pullover Hoodlie',
        only_x_left_in_stock: 156,
        price: {
            regularPrice: {
                amount: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 40,
                    percent_off: 57.14285714285714,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 70,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        redirect_code: 0,
        rating_summary: 10,
        review_count: 2,
        related_products: null,
        sku: 'WH01',
        small_image: {
            label: '',
            url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/products/492/401/wh01-green_main__96543.1690452070.jpg',
        },
        stock_status: 'IN_STOCK',
        url_key: 'mona-pullover-hoodlie',
        url_suffix: '',
        reviews: {
            items: [
                {
                    ratings_breakdown: [
                        {
                            name: 'John',
                            value: '',
                        },
                    ],
                    average_rating: 5,
                    created_at: '2019-08-24T14:15:22Z',
                    nickname: '',
                    summary: 'Great product',
                    text: 'I want more of this',
                    product: {},
                },
                {
                    ratings_breakdown: [
                        {
                            name: 'John',
                            value: '',
                        },
                    ],
                    average_rating: 5,
                    created_at: '2019-08-24T14:15:22Z',
                    nickname: '',
                    summary: 'Great product',
                    text: 'I want more of this',
                    product: {},
                },
            ],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        variants: [
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Green',
                        value_index: 182,
                        uid: 'MTgy',
                    },
                    {
                        code: 'size',
                        label: 'S',
                        value_index: 184,
                        uid: 'MTg0',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 1,
                            warningLevel: 2,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 2,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 2,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 513,
                    media_gallery_entries: [
                        {
                            disabled: false,
                            file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
                            id: 2888706,
                            label: '',
                            position: 0,
                            uid: '',
                        },
                    ],
                    only_x_left_in_stock: 5,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 40,
                                percent_off: 57.14285714285714,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 30,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 70,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 40,
                                percent_off: 57.14285714285714,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 30,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 70,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-S-Green',
                    small_image: {
                        label: '',
                        url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1MTM=',
                },
            },
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Green',
                        value_index: 182,
                        uid: 'MTgy',
                    },
                    {
                        code: 'size',
                        label: 'M',
                        value_index: 185,
                        uid: 'MTg1',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 41,
                            warningLevel: 2,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 20,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 514,
                    media_gallery_entries: [
                        {
                            disabled: false,
                            file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/57_source_1690452040.jpg',
                            id: 10945416,
                            label: '',
                            position: 0,
                            uid: '',
                        },
                    ],
                    only_x_left_in_stock: 71,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 17,
                                percent_off: 29.82456140350877,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 40,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 17,
                                percent_off: 29.82456140350877,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 40,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-M-Green',
                    small_image: {
                        label: '',
                        url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/57_source_1690452040.jpg',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1MTQ=',
                },
            },
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Purple',
                        value_index: 183,
                        uid: 'MTgz',
                    },
                    {
                        code: 'size',
                        label: 'S',
                        value_index: 184,
                        uid: 'MTg0',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 0,
                            warningLevel: 0,
                            isInStock: false,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 0,
                            warningLevel: 0,
                            isInStock: false,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 20,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 515,
                    media_gallery_entries: [
                        {
                            disabled: false,
                            file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/75_source_1698882973.jpg',
                            id: 1319280,
                            label: '',
                            position: 0,
                            uid: '',
                        },
                    ],
                    only_x_left_in_stock: 20,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-S-Purple',
                    small_image: {
                        label: '',
                        url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/75_source_1698882973.jpg',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1MTU=',
                },
            },
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Purple',
                        value_index: 183,
                        uid: 'MTgz',
                    },
                    {
                        code: 'size',
                        label: 'M',
                        value_index: 185,
                        uid: 'MTg1',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 0,
                            warningLevel: 0,
                            isInStock: false,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 516,
                    media_gallery_entries: [
                        {
                            disabled: false,
                            file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/56_source_1698882973.jpg',
                            id: 8969987,
                            label: '',
                            position: 0,
                            uid: '',
                        },
                    ],
                    only_x_left_in_stock: 20,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 47,
                                percent_off: 82.45614035087719,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 10,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 47,
                                percent_off: 82.45614035087719,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 10,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-M-Purple',
                    small_image: {
                        label: '',
                        url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/56_source_1698882973.jpg',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1MTY=',
                },
            },
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Light Blue',
                        value_index: 236,
                        uid: 'MjM2',
                    },
                    {
                        code: 'size',
                        label: 'S',
                        value_index: 184,
                        uid: 'MTg0',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 0,
                            warningLevel: 0,
                            isInStock: false,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 547,
                    media_gallery_entries: [],
                    only_x_left_in_stock: 20,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-LI-S',
                    small_image: {
                        label: '',
                        url: '',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1NDc=',
                },
            },
            {
                attributes: [
                    {
                        code: 'color',
                        label: 'Light Blue',
                        value_index: 236,
                        uid: 'MjM2',
                    },
                    {
                        code: 'size',
                        label: 'M',
                        value_index: 185,
                        uid: 'MTg1',
                    },
                ],
                product: {
                    by_location: [
                        {
                            locationEntityId: 1,
                            locationEntityCode: 'default',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 0,
                            warningLevel: 0,
                            isInStock: false,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 2,
                            locationEntityCode: 'BIGC-2',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                        {
                            locationEntityId: 3,
                            locationEntityCode: '',
                            locationEntityTypeId: 'PHYSICAL',
                            locationDistance: null,
                            availableToSell: 10,
                            warningLevel: 0,
                            isInStock: true,
                            __typename: 'ByLocation',
                        },
                    ],
                    custom_attributes: [],
                    id: 548,
                    media_gallery_entries: [],
                    only_x_left_in_stock: 20,
                    price_range: {
                        maximum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                        minimum_price: {
                            discount: {
                                amount_off: 0,
                                percent_off: 0,
                            },
                            final_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                            regular_price: {
                                currency: 'AUD',
                                value: 57,
                            },
                        },
                    },
                    price_tiers: [],
                    rating_summary: 0,
                    redirect_code: 0,
                    reviews: {
                        items: [],
                        page_info: {
                            current_page: 0,
                            page_size: 0,
                            total_pages: 0,
                        },
                    },
                    review_count: 0,
                    sku: 'WH01-LI-M',
                    small_image: {
                        label: '',
                        url: '',
                    },
                    staged: false,
                    stock_status: 'IN_STOCK',
                    uid: 'VmFyaWFudDo1NDg=',
                },
            },
        ],
        warranty: '',
        __typename: 'ConfigurableProduct',
        is_clothing: 'true',
        gender: 'm',
        is_bulky_item: '0',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 1,
                warningLevel: 2,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 2,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 2,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 513,
        media_gallery_entries: [
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
                id: 2888706,
                label: '',
                position: 0,
                uid: '',
            },
        ],
        only_x_left_in_stock: 5,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 40,
                    percent_off: 57.14285714285714,
                },
                final_price: {
                    currency: 'AUD',
                    value: 30,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 70,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 40,
                    percent_off: 57.14285714285714,
                },
                final_price: {
                    currency: 'AUD',
                    value: 30,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 70,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-S-Green',
        small_image: {
            label: '',
            url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1MTM=',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 41,
                warningLevel: 2,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 20,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 514,
        media_gallery_entries: [
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/57_source_1690452040.jpg',
                id: 10945416,
                label: '',
                position: 0,
                uid: '',
            },
        ],
        only_x_left_in_stock: 71,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 17,
                    percent_off: 29.82456140350877,
                },
                final_price: {
                    currency: 'AUD',
                    value: 40,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 17,
                    percent_off: 29.82456140350877,
                },
                final_price: {
                    currency: 'AUD',
                    value: 40,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-M-Green',
        small_image: {
            label: '',
            url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/57_source_1690452040.jpg',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1MTQ=',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 0,
                warningLevel: 0,
                isInStock: false,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 0,
                warningLevel: 0,
                isInStock: false,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 20,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 515,
        media_gallery_entries: [
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/75_source_1698882973.jpg',
                id: 1319280,
                label: '',
                position: 0,
                uid: '',
            },
        ],
        only_x_left_in_stock: 20,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-S-Purple',
        small_image: {
            label: '',
            url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/75_source_1698882973.jpg',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1MTU=',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 0,
                warningLevel: 0,
                isInStock: false,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 516,
        media_gallery_entries: [
            {
                disabled: false,
                file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/56_source_1698882973.jpg',
                id: 8969987,
                label: '',
                position: 0,
                uid: '',
            },
        ],
        only_x_left_in_stock: 20,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 47,
                    percent_off: 82.45614035087719,
                },
                final_price: {
                    currency: 'AUD',
                    value: 10,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 47,
                    percent_off: 82.45614035087719,
                },
                final_price: {
                    currency: 'AUD',
                    value: 10,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-M-Purple',
        small_image: {
            label: '',
            url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/56_source_1698882973.jpg',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1MTY=',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 0,
                warningLevel: 0,
                isInStock: false,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 547,
        media_gallery_entries: [],
        only_x_left_in_stock: 20,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-LI-S',
        small_image: {
            label: '',
            url: '',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1NDc=',
    },
    {
        by_location: [
            {
                locationEntityId: 1,
                locationEntityCode: 'default',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 0,
                warningLevel: 0,
                isInStock: false,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 2,
                locationEntityCode: 'BIGC-2',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
            {
                locationEntityId: 3,
                locationEntityCode: '',
                locationEntityTypeId: 'PHYSICAL',
                locationDistance: null,
                availableToSell: 10,
                warningLevel: 0,
                isInStock: true,
                __typename: 'ByLocation',
            },
        ],
        custom_attributes: [],
        id: 548,
        media_gallery_entries: [],
        only_x_left_in_stock: 20,
        price_range: {
            maximum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
            minimum_price: {
                discount: {
                    amount_off: 0,
                    percent_off: 0,
                },
                final_price: {
                    currency: 'AUD',
                    value: 57,
                },
                regular_price: {
                    currency: 'AUD',
                    value: 57,
                },
            },
        },
        price_tiers: [],
        rating_summary: 0,
        redirect_code: 0,
        reviews: {
            items: [],
            page_info: {
                current_page: 0,
                page_size: 0,
                total_pages: 0,
            },
        },
        review_count: 0,
        sku: 'WH01-LI-M',
        small_image: {
            label: '',
            url: '',
        },
        staged: false,
        stock_status: 'IN_STOCK',
        uid: 'VmFyaWFudDo1NDg=',
    },
];

export const transformedCartItems = [
    {
        id: 'df21b1d0-6178-454c-a159-699e80c7d8e0',
        uid: 'ZGYyMWIxZDAtNjE3OC00NTRjLWExNTktNjk5ZTgwYzdkOGUwLzQ5Mi81MTM=',
        customizable_options: [],
        errors: null,
        prices: {
            price: {
                currency: 'AUD',
                value: 30,
            },
            price_including_tax: {
                currency: 'AUD',
                value: 30,
            },
            row_total: {
                currency: 'AUD',
                value: 60,
            },
            row_total_including_tax: {
                currency: 'AUD',
                value: 60,
            },
            total_item_discount: {
                currency: 'AUD',
                value: 0,
            },
        },
        product: {
            by_location: [
                {
                    locationEntityId: 1,
                    locationEntityCode: 'default',
                    locationEntityTypeId: 'PHYSICAL',
                    locationDistance: null,
                    availableToSell: 1,
                    warningLevel: 2,
                    isInStock: true,
                    __typename: 'ByLocation',
                },
                {
                    locationEntityId: 2,
                    locationEntityCode: 'BIGC-2',
                    locationEntityTypeId: 'PHYSICAL',
                    locationDistance: null,
                    availableToSell: 2,
                    warningLevel: 0,
                    isInStock: true,
                    __typename: 'ByLocation',
                },
                {
                    locationEntityId: 3,
                    locationEntityCode: '',
                    locationEntityTypeId: 'PHYSICAL',
                    locationDistance: null,
                    availableToSell: 2,
                    warningLevel: 0,
                    isInStock: true,
                    __typename: 'ByLocation',
                },
            ],
            custom_attributes: [],
            id: 513,
            media_gallery_entries: [
                {
                    disabled: false,
                    file: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
                    id: 2888706,
                    label: '',
                    position: 0,
                    uid: '',
                },
            ],
            only_x_left_in_stock: 5,
            price_range: {
                maximum_price: {
                    discount: {
                        amount_off: 40,
                        percent_off: 57.14285714285714,
                    },
                    final_price: {
                        currency: 'AUD',
                        value: 30,
                    },
                    regular_price: {
                        currency: 'AUD',
                        value: 70,
                    },
                },
                minimum_price: {
                    discount: {
                        amount_off: 40,
                        percent_off: 57.14285714285714,
                    },
                    final_price: {
                        currency: 'AUD',
                        value: 30,
                    },
                    regular_price: {
                        currency: 'AUD',
                        value: 70,
                    },
                },
            },
            price_tiers: [],
            rating_summary: 0,
            redirect_code: 0,
            reviews: {
                items: [],
                page_info: {
                    current_page: 0,
                    page_size: 0,
                    total_pages: 0,
                },
            },
            review_count: 0,
            sku: 'WH01-S-Green',
            small_image: {
                label: '',
                url: 'https://cdn11.bigcommerce.com/s-xxazhvt7gd/images/stencil/500x245/attribute_rule_images/54_source_1690452039.jpg',
            },
            staged: false,
            stock_status: 'IN_STOCK',
            uid: 'VmFyaWFudDo1MTM=',
            brand: 'Weller',
            categories: [
                {
                    canonical_url: 'shop-all',
                    children: [],
                    children_count: '0',
                    description: '',
                    id: 23,
                    include_in_menu: 1,
                    level: 1,
                    meta_description: '',
                    meta_title: '',
                    name: 'Shop All',
                    path: '0/23',
                    position: 0,
                    products: null,
                    redirect_code: 0,
                    uid: 'MjM=',
                    url_path: 'shop-all',
                    url_suffix: '',
                    staged: false,
                    breadcrumbs: [],
                    __typename: 'CategoryTree',
                },
                {
                    canonical_url: 'whats-new',
                    children: [],
                    children_count: '0',
                    description: '',
                    id: 57,
                    include_in_menu: 1,
                    level: 1,
                    meta_description: 'This is the "What\'s New" meta_description',
                    meta_title: "What's New",
                    name: "What's New",
                    path: '0/57',
                    position: 0,
                    products: null,
                    redirect_code: 0,
                    uid: 'NTc=',
                    url_path: 'whats-new',
                    url_suffix: '',
                    staged: false,
                    breadcrumbs: [],
                    __typename: 'CategoryTree',
                },
                {
                    canonical_url: 'women',
                    children: [],
                    children_count: '0',
                    description: '',
                    id: 58,
                    include_in_menu: 1,
                    level: 1,
                    meta_description: 'This is the "Women" meta_description',
                    meta_title: 'Women',
                    name: 'Women',
                    path: '0/58',
                    position: 0,
                    products: null,
                    redirect_code: 0,
                    uid: 'NTg=',
                    url_path: 'women',
                    url_suffix: '',
                    staged: false,
                    breadcrumbs: [],
                    __typename: 'CategoryTree',
                    is_women_category: 'true',
                },
                {
                    canonical_url: 'women/tops',
                    children: [],
                    children_count: '0',
                    description: '',
                    id: 59,
                    include_in_menu: 1,
                    level: 2,
                    meta_description: '',
                    meta_title: '',
                    name: 'Tops',
                    path: '0/59',
                    position: 0,
                    products: null,
                    redirect_code: 0,
                    uid: 'NTk=',
                    url_path: 'women/tops',
                    url_suffix: '',
                    staged: false,
                    breadcrumbs: [
                        {
                            category_id: 58,
                            category_level: 1,
                            category_name: 'Women',
                            category_url_path: 'women',
                            category_url_key: 'women',
                            category_uid: 'NTg=',
                        },
                    ],
                    __typename: 'CategoryTree',
                },
                {
                    canonical_url: 'women/tops/hoodies-sweatshirts',
                    children: [],
                    children_count: '0',
                    description: '',
                    id: 60,
                    include_in_menu: 1,
                    level: 3,
                    meta_description: '',
                    meta_title: '',
                    name: 'Hoodies & Sweatshirts',
                    path: '0/60',
                    position: 0,
                    products: null,
                    redirect_code: 0,
                    uid: 'NjA=',
                    url_path: 'women/tops/hoodies-sweatshirts',
                    url_suffix: '',
                    staged: false,
                    breadcrumbs: [
                        {
                            category_id: 58,
                            category_level: 1,
                            category_name: 'Women',
                            category_url_path: 'women',
                            category_url_key: 'women',
                            category_uid: 'NTg=',
                        },
                        {
                            category_id: 59,
                            category_level: 2,
                            category_name: 'Tops',
                            category_url_path: 'women/tops',
                            category_url_key: 'women/tops',
                            category_uid: 'NTk=',
                        },
                    ],
                    __typename: 'CategoryTree',
                },
            ],
            name: 'Mona Pullover Hoodlie',
            url_key: 'mona-pullover-hoodlie',
            url_suffix: '',
            __typename: 'SimpleProduct',
        },
        quantity: 2,
        configurable_options: [
            {
                id: 148,
                option_label: 'Color',
                value_id: 182,
                value_label: 'Green',
            },
            {
                id: 149,
                option_label: 'Size',
                value_id: 184,
                value_label: 'S',
            },
        ],
        __typename: 'ConfigurableCartItem',
    },
];
