export const ACCESS_VALID_REFRESH_VALID = 'ACCESS_VALID_REFRESH_VALID';
export const ACCESS_INVALID_REFRESH_VALID = 'ACCESS_INVALID_REFRESH_VALID';
export const ACCESS_VALID_REFRESH_INVALID = 'ACCESS_VALID_REFRESH_INVALID';
export const ACCESS_INVALID_REFRESH_INVALID = 'ACCESS_INVALID_REFRESH_INVALID';

export enum JWT_AUTH_STATUSES {
    ACCESS_VALID_REFRESH_VALID,
    ACCESS_INVALID_REFRESH_VALID,
    ACCESS_VALID_REFRESH_INVALID,
    ACCESS_INVALID_REFRESH_INVALID,
}
