merger: stitching
sources:
  - name: TakeFlight
    handler:
      graphql:
        source: ./application
  # @TODO: Move this to a custom resolver
  - name: BigCommerceManagementRestApi
    handler:
      jsonSchema:
        endpoint: https://api.bigcommerce.com/stores/{env.STORE_HASH}
        operationHeaders:
          X-Auth-Token: '{env.X_AUTH_TOKEN}'
          Accept: application/json
          Content-Type: application/json
        operations:
          - type: Mutation
            field: createCartRedirectUrls #https://developer.bigcommerce.com/api-reference/ac0a56645afa2-create-cart-redirect-url
            path: /v3/carts/{args.cartId}/redirect_urls
            method: POST
            responseSample: ./schema/samples/carts/create-cart-redirect-urls-response.json
            argTypeMap:
              cartId:
                type: string
              queryParamArgMap:
                cartId: cartId

additionalEnvelopPlugins: './plugins/additional-plugins'

plugins:
  - hive:
      token: '{env.HIVE_TOKEN}'
      usage: !include '${STAGE}/hive-usage.yml'

serve: !include '${STAGE}/serve.yml'
cache: !include '${STAGE}/cache.yml'
